[project]
name = "openrocket-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "orhelper>=0.1.3",
    "pymoo>=0.6.0",
    "scipy>=1.17.0",
]
